//have to include the new file here if you create a new css file
import "./globals.css";
import { Inter } from "next/font/google";
/**
 * entry point of our app , this is the global page that will be present on every page inside the app like header, sidebar
 *  */
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
